export const QUESTION_CATEGORY = 'QUESTION_CATEGORY';
export const QUESTION_DIFFICULTY = "QUESTION_DIFFICULTY";
export const QUESTION_TYPE = "QUESTION_TYPE";
export const AMOUNT_OF_QUESTION = "AMOUNT_OF_QUESTION";
export const FINAL_SCORE = "FINAL_SCORE";